// let historyData = {
//   userOnline:0,
//   data: {
//     chatData: [
//       {
//         id_message: 1,
//         user_id: "1",
//         user_role: "1",
//         user_id_zoom: "497526",
//         user_name: "Raka",
//         avatar: "https://cdn.quasar.dev/img/avatar1.jpg",
//         data: {
//           message: "halo gess, saya raka. ini test kirim me",
//           url: null,
//         },
//         action: { desc: null, counter: null },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//         status: 1,
//       },
//       {
//         id_message: 21,
//         user_id: "1",
//         user_role: "1",
//         user_id_zoom: "497526",
//         user_name: "Raka",
//         avatar: "https://cdn.quasar.dev/img/avatar1.jpg",
//         data: {
//           message: "halo gess, saya raka. ini test kirim me",
//           url: null,
//         },
//         action: { desc: null, counter: null },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//         status: 2,
//       },
//       {
//         id_message: 22,
//         user_id: "1",
//         user_role: "1",
//         user_id_zoom: "497526",
//         user_name: "Raka",
//         avatar: "https://cdn.quasar.dev/img/avatar1.jpg",
//         data: {
//           message: "halo gess, saya raka. ini test kirim me",
//           url: null,
//         },
//         action: { desc: null, counter: null },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//         status: 2,
//       },
//       {
//         id_message: 2,
//         user_id: "2",
//         user_role: "1",
//         user_id_zoom: "497527",
//         user_name: "Sadam",
//         avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
//         data: {
//           message: "halo gess, saya sadam. ini test kirim you",
//           url: null,
//         },
//         action: { desc: null, counter: null },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//         status: 1,
//       },
//       {
//         id_message: 12,
//         user_id: "2",
//         user_role: "1",
//         user_id_zoom: "497527",
//         user_name: "Sadam",
//         avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
//         data: {
//           message: "halo gess, saya sadam. ini test kirim you",
//           url: null,
//         },
//         action: { desc: null, counter: null },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//         status: 1,
//       },
//       {
//         id_message: 14,
//         user_id: "2",
//         user_role: "1",
//         user_id_zoom: "497527",
//         user_name: "Sadam",
//         avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
//         data: {
//           message: "halo gess, saya sadam. ini test kirim you",
//           url: null,
//         },
//         action: { desc: null, counter: null },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//         status: 1,
//       },
//       {
//         id_message: 15,
//         user_id: "2",
//         user_role: "1",
//         user_id_zoom: "497527",
//         user_name: "Sadam",
//         avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
//         data: {
//           message: "halo gess, saya sadam. ini test kirim you",
//           url: null,
//         },
//         action: { desc: null, counter: null },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//         status: 1,
//       },
//       {
//         id_message: 16,
//         user_id: "2",
//         user_role: "1",
//         user_id_zoom: "497527",
//         user_name: "Sadam",
//         avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
//         data: {
//           message: "halo gess, saya sadam. ini test kirim you",
//           url: null,
//         },
//         action: { desc: null, counter: null },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//         status: 1,
//       },
//       {
//         id_message: 17,
//         user_id: "2",
//         user_role: "1",
//         user_id_zoom: "497527",
//         user_name: "Sadam",
//         avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
//         data: {
//           message: "halo gess, saya sadam. ini test kirim you",
//           url: null,
//         },
//         action: { desc: null, counter: null },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//         status: 1,
//       },
//       {
//         id_message: 18,
//         user_id: "2",
//         user_role: "1",
//         user_id_zoom: "497527",
//         user_name: "Sadam",
//         avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
//         data: {
//           message: "halo gess, saya sadam. ini test kirim you",
//           url: null,
//         },
//         action: { desc: null, counter: null },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//         status: 1,
//       },
//       {
//         id_message: 19,
//         user_id: "2",
//         user_role: "1",
//         user_id_zoom: "497527",
//         user_name: "Sadam",
//         avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
//         data: {
//           message: "halo gess, saya sadam. ini test kirim you",
//           url: null,
//         },
//         action: { desc: null, counter: null },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//         status: 1,
//       },
//       {
//         id_message: 110,
//         user_id: "2",
//         user_role: "1",
//         user_id_zoom: "497527",
//         user_name: "Sadam",
//         avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
//         data: {
//           message: "halo gess, saya sadam. ini test kirim you",
//           url: null,
//         },
//         action: { desc: null, counter: null },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//         status: 1,
//       },
//       {
//         id_message: 111,
//         user_id: "2",
//         user_role: "1",
//         user_id_zoom: "497527",
//         user_name: "Sadam",
//         avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
//         data: {
//           message: "halo gess, saya sadam. ini test kirim you",
//           url: null,
//         },
//         action: { desc: null, counter: null },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//         status: 1,
//       },
//       {
//         id_message: 112,
//         user_id: "2",
//         user_role: "1",
//         user_id_zoom: "497527",
//         user_name: "Sadam",
//         avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
//         data: {
//           message: "halo gess, saya sadam. ini test kirim you",
//           url: null,
//         },
//         action: { desc: null, counter: null },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//         status: 1,
//       },
//       {
//         id_message: 112,
//         user_id: "3",
//         user_role: "3",
//         user_id_zoom: "497527",
//         user_name: "Gilang",
//         avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
//         data: {
//           message: "halo gess, saya sadam. ini test kirim you",
//           url: null,
//         },
//         action: { desc: null, counter: null },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//         status: 1,
//       },
//       {
//         id_message: 3,
//         user_id: "3",
//         user_role: "3",
//         user_id_zoom: "497528",
//         user_name: "Sephikar",
//         avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
//         data: {
//           message: "Ahkam meminta untuk mengaktifkan mic",
//           url: null,
//         },
//         action: { desc: "mic", counter: 0 },
//         chat_type: 2,
//         timestamp: "2022-06-12 14:30:13",
//       },
//       {
//         id_message: 4,
//         user_id: "4",
//         user_role: "1",
//         user_id_zoom: "497529",
//         user_name: "Anda",
//         avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
//         data: {
//           message:
//             "Anda menerima permintaan ahkam untuk mengaktifkan mikrophone",
//           url: "",
//         },
//         action: { desc: "mic", counter: 1 },
//         chat_type: 2,
//         timestamp: "2022-06-12 14:30:13",
//       },
//       {
//         id_message: 5,
//         user_id: "4",
//         user_role: "1",
//         user_id_zoom: "497529",
//         user_name: "Anda",
//         avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
//         data: {
//           message: "Anda menolak permintaan Ahkam untuk mengaktifkan mic",
//           url: "",
//         },
//         action: { desc: "mic", counter: 2 },
//         chat_type: 2,
//         timestamp: "2022-06-12 14:30:13",
//       },
//       {
//         id_message: 6,
//         user_id: "1",
//         user_role: "1",
//         user_id_zoom: "497526",
//         user_name: "",
//         avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
//         data: {
//           message:
//             "Anda sedang menerima permintaan Ahkam untuk mengaktifkan mic",
//           url: "",
//         },
//         action: { desc: "mic", counter: 4 },
//         chat_type: 2,
//         timestamp: "2022-06-12 14:30:13",
//       },
//       {
//         id_message: 8,
//         user_id: "1",
//         user_role: "1",
//         user_id_zoom: "497526",
//         user_name: "",
//         avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
//         data: { message: "Panggilan telah berakhir", url: "" },
//         action: { desc: "mic", counter: 3 },
//         chat_type: 2,
//         timestamp: "2022-06-12 14:30:13",
//       },
//       {
//         id_message: 9,
//         user_id: "1",
//         user_role: "1",
//         user_id_zoom: "497526",
//         user_name: "",
//         avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
//         data: { message: "Panggilan telah berakhir", url: "" },
//         action: { desc: "mic", counter: 3 },
//         chat_type: 2,
//         timestamp: "2022-06-12 14:30:13",
//       },
//       {
//         id_message: 10,
//         user_id: "1",
//         user_role: "1",
//         user_id_zoom: "497526",
//         user_name: "",
//         avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
//         data: { message: "Panggilan telah berakhir", url: "" },
//         action: { desc: "mic", counter: 3 },
//         chat_type: 2,
//         timestamp: "2022-06-12 14:30:13",
//       },
//       {
//         id_message: 11,
//         user_id: "3",
//         user_role: "3",
//         user_id_zoom: "497526",
//         user_name: "Gilang",
//         avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
//         data: { message: "Sadam Husen alatas kirim pesan", url: "" },
//         action: { desc: "mic", counter: 3 },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//       },
//       {
//         id_message: 11,
//         user_id: "2",
//         user_role: "1",
//         user_id_zoom: "10080568",
//         user_name: "Lani",
//         avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
//         data: {
//           message: "Sadam Husen alatas kirim pesan nih ${Constant.dummyText}",
//           url: "",
//         },
//         action: { desc: "mic", counter: 3 },
//         chat_type: 1,
//         timestamp: "2022-06-12 14:30:13",
//       },
//     ],
//   },
// };
let historyDatas = {
  userOnline:0,
  data: {
    chatData: [
      {
        id_message: 1,
        user_id: "1",
        user_role: "1",
        user_id_zoom: "497526",
        user_name: "Raka",
        avatar: "https://cdn.quasar.dev/img/avatar1.jpg",
        data: {
          message: "halo gess, saya raka. ini test kirim me",
          url: null,
          fileName: null
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 1,
      },
      {
        id_message: 21,
        user_id: "1",
        user_role: "1",
        user_id_zoom: "497526",
        user_name: "Raka",
        avatar: "https://cdn.quasar.dev/img/avatar1.jpg",
        data: {
          message: "halo gess, saya raka. ini test kirim me",
          url: null,
          fileName: null
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 2,
      },
      {
        id_message: 22,
        user_id: "1",
        user_role: "1",
        user_id_zoom: "497526",
        user_name: "Raka",
        avatar: "https://cdn.quasar.dev/img/avatar1.jpg",
        data: {
          message: "halo gess, saya raka. ini test kirim me",
          url: null,
          fileName: null
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 2,
      },
      {
        id_message: 2,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 1,
      },
      {
        id_message: 12,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 1,
      },
      {
        id_message: 14,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 1,
      },
      {
        id_message: 15,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 1,
      },
      {
        id_message: 16,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 1,
      },
      {
        id_message: 17,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 1,
      },
      {
        id_message: 18,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 1,
      },
      {
        id_message: 19,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 1,
      },
      {
        id_message: 110,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 1,
      },
      {
        id_message: 111,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 1,
      },
      {
        id_message: 112,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null
        },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        action: { desc: null, counter: null },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 1,
      },
      {
        id_message: 112,
        user_id: "3",
        user_role: "3",
        user_id_zoom: "497527",
        user_name: "Gilang",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 1,
      },
      {
        id_message: 3,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Ahkam meminta untuk mengaktifkan mic",
          url: null,
          fileName: null
        },
        action: { desc: "mic", counter: 0 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 2,
        timestamp: "2022-06-12 14:30:13",
      },
      {
        id_message: 4,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message:
            "Anda menerima permintaan ahkam untuk mengaktifkan mikrophone",
          url: "",
          fileName: null
        },
        action: { desc: "mic", counter: 1 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 2,
        timestamp: "2022-06-12 14:30:13",
      },
      {
        id_message: 5,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Anda menolak permintaan Ahkam untuk mengaktifkan mic",
          url: "",
          fileName: null
        },
        action: { desc: "mic", counter: 2 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 2,
        timestamp: "2022-06-12 14:30:13",
      },
      {
        id_message: 6,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message:
            "Anda sedang menerima permintaan Ahkam untuk mengaktifkan mic",
          url: "",
          fileName: null
        },
        action: { desc: "mic", counter: 4 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 2,
        timestamp: "2022-06-12 14:30:13",
      },
      {
        id_message: 8,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: { message: "Panggilan telah berakhir", url: "" },
        action: { desc: "mic", counter: 3 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 2,
        timestamp: "2022-06-12 14:30:13",
      },
      {
        id_message: 9,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Panggilan telah berakhir",
          url: "",
          fileName: null,
        },
        action: { desc: "mic", counter: 3 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 2,
        timestamp: "2022-06-12 14:30:13",
      },
      {
        id_message: 10,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Panggilan telah berakhir",
          url: "",
          fileName: null,
        },
        action: { desc: "mic", counter: 3 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 2,
        timestamp: "2022-06-12 14:30:13",
      },
      {
        id_message: 11,
        user_id: "3",
        user_role: "3",
        user_id_zoom: "497526",
        user_name: "Gilang",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Sadam Husen alatas kirim pesan",
          url: "",
          fileName: null,
        },
        action: { desc: "mic", counter: 3 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
      },
      {
        id_message: 11,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "10080568",
        user_name: "Lani",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Sadam Husen alatas kirim pesan nih ${Constant.dummyText}",
          url: "",
          fileName: null,
        },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        action: { desc: "mic", counter: 3 },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
      },
      // contoh siswa mengajukan call (SISWA)
      {
        id_message: 13,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "10080568",
        user_name: "Lani",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Kamu berhasil mengajukan call",
          url: "",
          fileName: null,
        },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        action: { desc: "mic", counter: 0 },
        chat_type: 4,
        timestamp: "2022-06-12 14:30:13",
      },
      // menerima pengajuan call dari murid (GURU)
      {
        id_message: 14,
        user_id: "34221",
        user_role: "3",
        user_id_zoom: "10080568",
        user_name: "Raka",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Kamu menerima pengajuan call dari: ....",
          url: "",
          fileName: null,
        },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        action: { desc: "mic", counter: 0 },
        chat_type: 4,
        timestamp: "2022-06-12 14:30:13",
      },
      // contoh siswa menerima acc call (SISWA)
      {
        id_message: 15,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "10080568",
        user_name: "Lani",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Call kmau berhasil diterima",
          url: "",
          fileName: null,
        },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        action: { desc: "mic", counter: 1 },
        chat_type: 4,
        timestamp: "2022-06-12 14:30:13",
      },
      // contoh guru menerima acc call (GURU)
      {
        id_message: 16,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Call berhasil diterima",
          url: "",
          fileName: null,
        },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        action: { desc: "mic", counter: 1 },
        chat_type: 2,
        timestamp: "2022-06-12 14:30:13",
      },
      {
        id_message: 14,
        user_id: "34221",
        user_role: "3",
        user_id_zoom: "10080568",
        user_name: "Raka",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "",
          url: "staging-guru.kelaspintar.id/testUpload.pdf",
          fileName: 'testUpload.pdf'
        },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2
        },
        action: { desc: "upload", counter: 1 },
        chat_type: 3,
        timestamp: "2022-06-12 14:30:13",
      },
    ],
  },
};
module.exports = historyDatas;
