let historyDatas = {
  userOnline: 0,
  data: {
    chatData: [
      {
        id_message: 1,
        user_id: "1",
        user_role: "1",
        user_id_zoom: "497526",
        user_name: "Raka",
        avatar: "https://cdn.quasar.dev/img/avatar1.jpg",
        data: {
          message: "halo gess, saya raka. ini test kirim me",
          url: null,
          fileName: null,
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:30:13",
        status: 1,
      },
      {
        id_message: 2,
        user_id: "1",
        user_role: "1",
        user_id_zoom: "497526",
        user_name: "Raka",
        avatar: "https://cdn.quasar.dev/img/avatar1.jpg",
        data: {
          message: "halo gess, saya raka. ini test kirim me",
          url: null,
          fileName: null,
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:31:13",
        status: 2,
      },
      {
        id_message: 3,
        user_id: "1",
        user_role: "1",
        user_id_zoom: "497526",
        user_name: "Raka",
        avatar: "https://cdn.quasar.dev/img/avatar1.jpg",
        data: {
          message: "halo gess, saya raka. ini test kirim me",
          url: null,
          fileName: null,
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:32:13",
        status: 2,
      },
      {
        id_message: 4,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null,
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:33:13",
        status: 1,
      },
      {
        id_message: 5,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null,
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:34:13",
        status: 1,
      },
      {
        id_message: 6,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null,
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:35:13",
        status: 1,
      },
      {
        id_message: 7,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null,
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:36:13",
        status: 1,
      },
      {
        id_message: 8,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null,
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:37:13",
        status: 1,
      },
      {
        id_message: 9,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null,
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:38:13",
        status: 1,
      },
      {
        id_message: 10,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null,
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:39:13",
        status: 1,
      },
      {
        id_message: 11,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null,
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:40:13",
        status: 1,
      },
      {
        id_message: 12,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null,
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:41:13",
        status: 1,
      },
      {
        id_message: 13,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null,
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:42:13",
        status: 1,
      },
      {
        id_message: 14,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "497527",
        user_name: "Sadam",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null,
        },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        action: { desc: null, counter: null },
        chat_type: 1,
        timestamp: "2022-06-12 14:43:13",
        status: 1,
      },
      {
        id_message: 15,
        user_id: "3",
        user_role: "3",
        user_id_zoom: "497527",
        user_name: "Gilang",
        avatar: "https://cdn.quasar.dev/img/avatar2.jpg",
        data: {
          message: "halo gess, saya sadam. ini test kirim you",
          url: null,
          fileName: null,
        },
        action: { desc: null, counter: null },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:44:13",
        status: 1,
      },
      {
        id_message: 16,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Ahkam meminta untuk mengaktifkan mic",
          url: null,
          fileName: null,
        },
        action: { desc: "mic", counter: 0 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 2,
        timestamp: "2022-06-12 14:45:13",
      },
      {
        id_message: 17,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message:
            "Anda menerima permintaan ahkam untuk mengaktifkan mikrophone",
          url: "",
          fileName: null,
        },
        action: { desc: "mic", counter: 1 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 2,
        timestamp: "2022-06-12 14:46:13",
      },
      {
        id_message: 18,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Anda menolak permintaan Ahkam untuk mengaktifkan mic",
          url: "",
          fileName: null,
        },
        action: { desc: "mic", counter: 2 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 2,
        timestamp: "2022-06-12 14:47:13",
      },
      {
        id_message: 19,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message:
            "Anda sedang menerima permintaan Ahkam untuk mengaktifkan mic",
          url: "",
          fileName: null,
        },
        action: { desc: "mic", counter: 4 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 2,
        timestamp: "2022-06-12 14:48:13",
      },
      {
        id_message: 20,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: { message: "Panggilan telah berakhir", url: "" },
        action: { desc: "mic", counter: 3 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 2,
        timestamp: "2022-06-12 14:49:13",
      },
      {
        id_message: 21,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Panggilan telah berakhir",
          url: "",
          fileName: null,
        },
        action: { desc: "mic", counter: 3 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 2,
        timestamp: "2022-06-12 14:50:13",
      },
      {
        id_message: 22,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Panggilan telah berakhir",
          url: "",
          fileName: null,
        },
        action: { desc: "mic", counter: 3 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 2,
        timestamp: "2022-06-12 14:51:13",
      },
      {
        id_message: 23,
        user_id: "3",
        user_role: "3",
        user_id_zoom: "497526",
        user_name: "Gilang",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Sadam Husen alatas kirim pesan",
          url: "",
          fileName: null,
        },
        action: { desc: "mic", counter: 3 },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:52:13",
      },
      {
        id_message: 24,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "10080568",
        user_name: "Lani",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Sadam Husen alatas kirim pesan nih ${Constant.dummyText}",
          url: "",
          fileName: null,
        },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        action: { desc: "mic", counter: 3 },
        chat_type: 1,
        timestamp: "2022-06-12 14:53:13",
      },
      // contoh siswa mengajukan call (SISWA)
      {
        id_message: 25,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "10080568",
        user_name: "Lani",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Kamu berhasil mengajukan call",
          url: "",
          fileName: null,
        },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        action: { desc: "mic", counter: 0 },
        chat_type: 4,
        timestamp: "2022-06-12 14:54:13",
      },
      // menerima pengajuan call dari murid (GURU)
      {
        id_message: 26,
        user_id: "34221",
        user_role: "3",
        user_id_zoom: "10080568",
        user_name: "Raka",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Kamu menerima pengajuan call dari: ....",
          url: "",
          fileName: null,
        },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        action: { desc: "mic", counter: 0 },
        chat_type: 4,
        timestamp: "2022-06-12 14:55:13",
      },
      // contoh siswa menerima acc call (SISWA)
      {
        id_message: 27,
        user_id: "2",
        user_role: "1",
        user_id_zoom: "10080568",
        user_name: "Lani",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Call kmau berhasil diterima",
          url: "",
          fileName: null,
        },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        action: { desc: "mic", counter: 1 },
        chat_type: 4,
        timestamp: "2022-06-12 14:56:13",
      },
      // contoh guru menerima acc call (GURU)
      {
        id_message: 28,
        user_id: "890",
        user_role: "3",
        user_id_zoom: "497528",
        user_name: "Guru Sephikar",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Call berhasil diterima",
          url: "",
          fileName: null,
        },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        action: { desc: "mic", counter: 1 },
        chat_type: 2,
        timestamp: "2022-06-12 14:57:13",
      },
      {
        id_message: 29,
        user_id: "34221",
        user_role: "3",
        user_id_zoom: "10080568",
        user_name: "Raka",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "",
          url: "staging-guru.kelaspintar.id/testUpload.pdf",
          fileName: "testUpload.pdf",
        },
        infoAssign: {
          id_user_teacher: 34221,
          id_user_student: 2,
        },
        action: { desc: "upload", counter: 0 },
        chat_type: 3,
        timestamp: "2022-06-12 14:58:13",
      },
      {
        id_message: 30,
        user_id: "13376649",
        user_role: "3",
        user_id_zoom: "10080568",
        user_name: "jo",
        avatar: "https://cdn.quasar.dev/img/avatar3.jpg",
        data: {
          message: "Jo Mengirim pesan",
          url: "",
          fileName: "",
        },
        infoAssign: {
          id_user_student: 13376649,
          id_user_teacher: 890,
        },
        action: {
          desc: "upload",
          counter: 0,
        },
        chat_type: 1,
        timestamp: "2022-06-12 14:59:13",
      },
    ],
  },
};
module.exports = historyDatas;
